version: '3.8'

services:
  # Servicio web Apache y PHP
  web:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./error_pages:/var/www/error_pages
      - ./ssl:/etc/ssl/private
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  # Servicio de base de datos MySQL
  db:
    image: mariadb:11.1
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gastos
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
    ports:
      - "3306:3306"

  # Servicio phpMyAdmin para la administración de la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - mynetwork
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db


volumes:
  db_data:




